version: '3.2'
services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: evermos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: B!sm!ll4h
    ports:
      - "5432:5432"
  run-migrations:
    build: .
    restart: on-failure
    environment:
      POSTGRES_DB: evermos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: B!sm!ll4h
      POSTGRES_URL: db:5432
    command: > 
      bash -c "
        flask db init && 
        flask db migrate && 
        flask db upgrade"
    depends_on:
      - db
  api:
    build: .
    restart: on-failure
    environment:
      POSTGRES_DB: evermos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: B!sm!ll4h
      POSTGRES_URL: db:5432
    ports:
      - "5000:5000"